import styled from "@emotion/styled";

export const Wrapper = styled.div``;
export const Header = styled.div``;
export const HeaderText = styled.div``;
export const Body = styled.div``;
export const Label = styled.div``;
export const Input_1 = styled.div``;
export const Textarea_1 = styled.div``;
export const MapWrapper = styled.div``;
export const MapPosition = styled.div``;
export const MapRightWrapper = styled.div``;
export const GPSWrapper = styled.div``;
export const LATDiv = styled.div``;
export const PositionIcon = styled.div``;
export const LNGDiv = styled.div``;
export const AddressWrapper = styled.div``;
export const Input_2 = styled.div``;
export const ImgWrapper = styled.div``;
export const ImgUpload = styled.div``;
export const RadioButtonWrapper = styled.div``;
export const RadioButton = styled.div``;
export const RadioLabel = styled.div``;
export const SubmitButton = styled.div``;
